[package]
name = "juro"
version = "0.0.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", default-features = false }