services:
  juro:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - net
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
networks:
  net:
    external: true
